---
title: I'm Only Blogging
author: R package build
hidedate: TRUE
slug: []
categories:
  - writing
---

Welcome. 

I made a New Year's resolution to try and be more creative in 2023. So, with 
that in mind, I will be trying my hand at a bit of writing in my spare time.

They say you can only hope to write songs as good as your record collection... 
so expect some very amateurish imitations of 
[Hemingway](https://en.wikipedia.org/wiki/Ernest_Hemingway), 
[Camus](https://en.wikipedia.org/wiki/Albert_Camus) and 
[Kerouac](https://en.wikipedia.org/wiki/Jack_Kerouac)!

The name of this website comes from one of my favourite Bob Dylan songs: 
[It's Alright Ma (I’m Only Bleeding)](https://www.bobdylan.com/songs/its-alright-ma-im-only-bleeding/).
Therefore, what better way to begin, than by trying to write another three 
verses of this masterpiece; with a modern twist. A cynical world view, 
alliteration and internal rhymes are the name of the game here. 

> Silent screens dictate the rules   
As folk seek solace in the cyber cesspool  
Chasing hits and likes from online ghouls  
Faking content to make their users drool   
Forsake themselves for digital jewels  
And wonder why they feel empty   
> 
> For the market's hunger knows no bounds  
It consumes the soul as greed is crowned   
In a plastic palace raised from the ground   
While the endless race to grow and compound  
Makes it impossible for the truth to be found   
That enough is more than plenty   
>  
> In this age of noise, where silence flees   
We shout for meaning, drowning in the seas  
Of shallow thoughts and easy tease  
We drift apart with inevitable ease   
Yet before the screens we're on our knees    
Praying for an iPhone 20 
>       
> But don't mind too much what I write  
It's only a feather in a cannon fight  
It’s alright, Ma, I’m only blogging 

Apologies to all Dylanolgists out there!

And now for the man himself:

<iframe width="100%" height="315" src="https://www.youtube.com/embed/JBNWkCsmqAY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

