---
title: "Reading"
menu: main
weight: 3
hidedate: TRUE
disable_comments: TRUE
---

```{r, echo=FALSE}
nstars <- function(n){
  paste0(rep('&#11089;', n), collapse = "")
}

books <- tibble::tribble(
  ~title, ~author, ~date, ~rating,
  "[Hotel Avacado](https://uk.bookshop.org/a/9445/9781398529625)", "Bob Mortimer", "2024-09-05", nstars(4),
  "[Timecode of a Face](https://uk.bookshop.org/a/9445/9781838855901)", "Ruth Ozeki", "2024-09-03", nstars(3),
  "[Restless Republic](https://uk.bookshop.org/a/9445/9780008282059)", "Anna Keay", "2024-08-30", nstars(3),
  "[A Big Sleep](https://uk.bookshop.org/a/9445/9780241654149)", "Raymond Chandler", "2024-08-04", nstars(2),
  "[A Tale of Two Cities](https://uk.bookshop.org/a/9445/9781912714964)", "Charles Dickens", "2024-07-11", nstars(3),
  "[Sharpe's Fortress](https://uk.bookshop.org/a/9445/9780007425846)", "Bernard Cornwell", "2024-06-23", nstars(3), 
  "[The Most Beautiful Woman in Town](https://uk.bookshop.org/a/9445/9780753513774)", "Charles Bukowski", "2024-06-01", nstars(4),
  "[James](https://uk.bookshop.org/a/9445/9781035031238)", "Percival Everett", "2024-05-03", nstars(4),
  "[A Farewell To Arms](https://uk.bookshop.org/a/9445/9780099273974)", "Ernest Hemingway", "2024-04-18", nstars(5),
  "[Sharpe's Fortress](https://uk.bookshop.org/a/9445/9780007425815)", "Bernard Cornwell", "2024-04-05", nstars(3), 
  "[The Sun Also Rises](https://uk.bookshop.org/a/9445/9780099285038)", "Ernest Hemingway", "2024-03-22", nstars(5),
  "[Sharpe's Triumph](https://uk.bookshop.org/a/9445/9780007425808)", "Bernard Cornwell", "2024-03-16", nstars(3),
  "[Act of Oblivion](https://uk.bookshop.org/a/9445/9781529160321)", "Robert Harris", "2024-03-02",
  nstars(4),
  "[The Bee Sting](https://uk.bookshop.org/a/9445/9780241984406)", "Paul Murray", "2024-02-13", nstars(4),
  "[Prophet Song](https://uk.bookshop.org/a/9445/9780861545896)", "Paul Lynch", "2024-01-22", nstars(5),
  "[In These Times](https://uk.bookshop.org/a/9445/9780571269532)", "Jenny Uglow", "2024-01-03", nstars(3),
  "[The Grim Smile of the Five Towns](https://uk.bookshop.org/a/9445/9783734087844)", "Arnold Bennett", "2023-12-09", nstars(3),
  "[Sharpe's Tiger](https://uk.bookshop.org/a/9445/9780007425792)", "Bernard Cornwell", "2023-12-02", nstars(4),
  "[The Last Devil To Die](https://uk.bookshop.org/a/9445/9780241512449)", "Richard Osman", "2023-11-10", nstars(3),
  "[The Iliad](https://uk.bookshop.org/a/9445/9781324001805)", "Homer (Emily Wilson)", "2023-11-01", nstars(3),
  "[Master and Commander](https://uk.bookshop.org/a/9445/9780006499152)", "Patrick O'Brian", "2023-10-07", nstars(3),
  "[The Fraud](https://uk.bookshop.org/a/9445/9780241336991)", "Zadie Smith", "2023-09-30", nstars(2),
  "[Old God's Time](https://uk.bookshop.org/a/9445/9780571332793)", "Sebastian Barry", "2023-09-10", nstars(3),
  "[State of Emergency](https://uk.bookshop.org/a/9445/9780141032153)", "Dominic Sandbrook", "2023-08-29", nstars(4), 
  "[First Person Singular](https://uk.bookshop.org/a/9445/9781529113594)", "Haruki Murakami", "2023-08-14", nstars(3),
  "[The Dhama Bums](https://uk.bookshop.org/a/9445/9780241348062)", "Jack Kerouac", "2023-07-30", nstars(5),
  "[A Moveable Feast](https://uk.bookshop.org/a/9445/9780099285045)", "Ernest Hemingway", "2023-07-27", nstars(5),
  "[The Book of Form and Emptiness](https://uk.bookshop.org/a/9445/9781838855277)", "Ruth Ozeki", "2023-07-25", nstars(4),
  "[Inverting the Pyramid](https://uk.bookshop.org/a/9445/9781399610094)", "Jonathan Wilson", "2023-07-18", nstars(3),
  "[An Instance of the Fingerpost](https://uk.bookshop.org/a/9445/9780099751816)", "Iain Pears", "2023-07-04", nstars(4),
  "[Ultra-Processed People](https://uk.bookshop.org/a/9445/9781529900057)", "Chris van Tulleken", "2023-06-14", nstars(3),
  "[Billy Summers](https://uk.bookshop.org/a/9445/9781529365702)", "Stephen King", "2023-05-28", nstars(3),
  "[Dictator](https://uk.bookshop.org/a/9445/9780099474197)", "Robert Harris", "2023-05-14", nstars(3),
  "[Black and British](https://uk.bookshop.org/a/9445/9781529065602)", "David Olusoga", "2023-04-29", nstars(4),
  "[The Trees](https://uk.bookshop.org/a/9445/9781035036615)", "Percival Everett", "2023-04-20", nstars(4),
  "[Booth](https://uk.bookshop.org/a/9445/9781788168649)", "Karen Joy Fowler", "2023-04-10", nstars(2),
  "[The Colony](https://uk.bookshop.org/a/9445/9780571367610)", "Audrey Magee", "2023-04-01", nstars(5),
  "[Case Study](https://uk.bookshop.org/a/9445/9781913393441)", "Graeme Macrae Burnet", "2023-03-23", nstars(5),
  "[Being Geoffrey Boycott](https://uk.bookshop.org/a/9445/9781915237064)", "Geoffrey Boycott", "2023-03-20", nstars(3),
  "[Lustrum](https://uk.bookshop.org/a/9445/9780099406327)", "Robert Harris", "2023-03-12", nstars(3),
  "[Days Without End](https://uk.bookshop.org/a/9445/9780571340224)", "Sebastian Barry", "2023-03-06", nstars(4),
  "[Imperium](https://uk.bookshop.org/a/9445/9780099527664)", "Robert Harris", "2023-02-27", nstars(3),
  "[Two Brothers](https://uk.bookshop.org/a/9445/9781408714492)", "Jonathan Wilson", "2023-02-23", nstars(3),
  "[Dance Dance Dance](https://uk.bookshop.org/a/9445/9780099448761)", "Haruki Murakami", "2023-02-20", nstars(3),
  "[The Old Wives' Tale](https://uk.bookshop.org/a/9445/9780099595359)", "Arnold Bennet", "2023-02-07", nstars(4),
  "[Money](https://uk.bookshop.org/a/9445/9780099461883)", "Martin Amis", "2023-01-27", nstars(4),
  "[Rogue Heroes](https://uk.bookshop.org/a/9445/9780241996904)", "Ben Macintyre", "2023-01-17", nstars(3),
  "[White Heat](https://uk.bookshop.org/a/9445/9780349118208)", "Dominic Sandbrook", "2023-01-14", nstars(4),
  "[Hamnet](https://uk.bookshop.org/a/9445/9781472223821)", "Maggie O'Farrell", "2023-01-12", nstars(2),
  "[The Silence Of The Girls](https://uk.bookshop.org/a/9445/9780241983201)", "Pat Barker", "2023-01-07", nstars(5),
  "[The Spy Who Came in from the Cold](https://uk.bookshop.org/a/9445/9780241978955)", "John le Carre", "2022-12-31", nstars(4),
  "[Lucky Jim](https://uk.bookshop.org/a/9445/9780241956847)", "Kingsley Amis", "2022-12-22", nstars(3),
  "[Never Had It So Good](https://uk.bookshop.org/a/9445/9780349115306)", "Dominic Sandbrook", "2022-12-14", nstars(4),
  "[Portrait of The Artist As A Young Man](https://uk.bookshop.org/a/9445/9780241405895)", "James Joyce", "2022-11-30", nstars(3),
  "[Portrait of The Artist As A Young Dog](https://uk.bookshop.org/a/9445/9781780227276)", "Dylan Thomas", "2022-11-12", nstars(2),
  "[The Satsuma Complex](https://uk.bookshop.org/a/9445/9781398521209)", "Bob Mortimer", "2022-11-03", nstars(4),
  "[Shakespeare](https://uk.bookshop.org/a/9445/9780007197903)", "Bill Bryson", "2022-10-12",nstars(3),
  "[The Bullet That Missed](https://uk.bookshop.org/a/9445/9780241512425)", "Richard Osman", "2022-10-06", nstars(3),
  "[A Brief History of Seven Killings](https://uk.bookshop.org/a/9445/9781780746357)", "Marlon James", "2022-09-29", nstars(2),
  "[Different Seasons](https://uk.bookshop.org/a/9445/9781444723601)", "Stephen King", "2022-08-31", nstars(5),
  "[The Five](https://uk.bookshop.org/a/9445/9781784162344)", "Hallie Rubenhold", "2022-08-02", nstars(4),
  "[Shuggie Bain](https://uk.bookshop.org/a/9445/9781529019292)", "Douglas Stuart", "2022-07-13", nstars(4),
  "[The War On The West](https://uk.bookshop.org/a/9445/9780008492496)", "Douglas Murray", "2022-06-14", nstars(1),
  "[The Man Who Died Twice](https://uk.bookshop.org/a/9445/9780241425428)", "Richard Osman", "2022-05-27", nstars(3),
  "[Jamaica Inn](https://uk.bookshop.org/a/9445/9780349006581)", "Daphne Du Maurier", "2022-05-11", nstars(3),
  "[Men At Arms](https://uk.bookshop.org/a/9445/9780141185736)", "Evelyn Waugh", "2022-04-20", nstars(3),
  "[Piranesi](https://uk.bookshop.org/a/9445/9781526622433)", "Susanna Clarke", "2022-03-29", nstars(3),
  "[Project Hail Mary](https://uk.bookshop.org/a/9445/9781529157468)", "Andy Weir", "2022-03-20", nstars(1),
  "[Invisible Man](https://uk.bookshop.org/a/9445/9780141184425)", "Ralph Ellison", "2022-03-01", nstars(4),
  "[The First Forty-Nine Stories](https://uk.bookshop.org/a/9445/9780099339212)", "Ernest Hemingway", "2022-02-16", nstars(5),
  "[Gilead](https://uk.bookshop.org/a/9445/9781844081486)", "Marilynne Robinson", "2022-01-14", nstars(3),
  "[A Christmas Carol](https://uk.bookshop.org/a/9445/9780140439052)", "Charles Dickens", "2021-12-24", nstars(4),
  "[Hard Times](https://uk.bookshop.org/a/9445/9781784873431)", "Charles Dickens", "2021-12-20", nstars(3),
  "[The Mirror And The Light](https://uk.bookshop.org/a/9445/9780007481002)", "Hilary Mantel", "2021-11-28", nstars(4),
  "[Bringing Up The Bodies](https://uk.bookshop.org/a/9445/9780008381684)", "Hilary Mantel", "2021-11-17", nstars(5),
  "[Wolf Hall](https://uk.bookshop.org/a/9445/9780008381691)", "Hilary Mantel", "2021-11-10", nstars(4),
  "[Pachinko](https://uk.bookshop.org/a/9445/9781786691378)", "Min Jin Lee", "2021-11-01", nstars(3),
  "[Chronicles](https://uk.bookshop.org/a/9445/9780743478649)", "Bob Dylan", "2021-10-24", nstars(4),
  "[The Time Traveller's Guide to Regency Britain](https://uk.bookshop.org/a/9445/9781784705961)", "Ian Mortimer", "2021-10-16", nstars(3),
)
```

```{r, echo = FALSE}
table <- knitr::kable(books, col.names = rep("", 4), "html", escape = FALSE)
kableExtra::kable_styling(table, full_width = TRUE)
```
